//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYNHOM9
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUSACH
    {
        public string ID { get; set; }
        public string MaSach { get; set; }
        public string Hoten { get; set; }
        public string Diachi { get; set; }
        public string Tensach { get; set; }
        public string Tinhtrang { get; set; }
        public Nullable<System.DateTime> Thoigianmuon { get; set; }
        public Nullable<System.DateTime> Thoigiantra { get; set; }
    
        public virtual KESACH KESACH { get; set; }
    }
}
