//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYNHOM9
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string ID { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public string MaSach { get; set; }
        public string GiaSach { get; set; }
        public string SoLuong { get; set; }
        public string NXB { get; set; }
    
        public virtual KESACH KESACH { get; set; }
    }
}
